version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  db_data:
